import type { EventItem } from "~/types/event";

export const initialEvents: EventItem[] = [
  {
    id: 1,
    name: "Music Festival",
    startDate: 1789687013,
    endDate: 1789859813,
    eventType: "Exhibition",
    venue: ["Hall 1", "Hall 2"],
    area: 30000,
    organizer: "ABC Events",
    // expectedPeople: 5000,
    level: "High",
    manager: "John Doe",
    status: "Upcoming",
  },
  {
    id: 2,
    name: "Tech Conference",
    startDate: 1789687013,
    endDate: 1789859813,
    eventType: "Meeting",
    venue: ["VIP Meeting Room"],
    area: 20000,
    organizer: "XYZ Tech",
    // expectedPeople: 2000,
    level: "Medium",
    manager: "Jane Smith",
    status: "Upcoming",
  },
  {
    id: 3,
    name: "Food Expo",
    startDate: 1789687013,
    endDate: 1789687013,
    eventType: "Exhibition",
    venue: ["Expo Hall"],
    area: 15000,
    organizer: "Foodies United",
    // expectedPeople: 3000,
    level: "Low",
    manager: "Alice Johnson",
    status: "Completed",
  },
];
